const weatherCodeDescription = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'Partly cloudy',
    3: 'Overcast',
    4: 'Smoky',
    5: 'Hazy',
    6: 'Dusty',
    7: 'Dust or sand',
    8: 'Sand whirls',
    9: 'Duststorm',
    10: 'Mist',
    11: 'Light fog',
    12: 'Shallow fog',
    13: 'Silent lightning',
    14: 'Visible precipitation',
    15: 'Distant precipitation',
    16: 'Nearby precipitation',
    17: 'Dry thunderstorm',
    18: 'Visible squalls',
    19: 'Funnel clouds',
    20: 'Drizzle or snow grains',
    21: 'Rain',
    22: 'Snowfall',
    23: 'Mixed precipitation',
    24: 'Freezing precipitation',
    25: 'Rain showers',
    26: 'Mixed showers',
    27: 'Hail showers',
    28: 'Fog',
    29: 'Thunderstorm',
    30: 'Decreasing storm',
    31: 'Stable',
    32: 'Intensifying',
    33: 'Decreasing severe storm',
    34: 'Stable',
    35: 'Intensifying',
    36: 'Light blowing snow',
    37: 'Heavy drifting snow',
    38: 'Moderate blowing snow',
    39: 'Heavy drifting snow',
    40: 'Distant fog',
    41: 'Fog patches',
    42: 'Thin fog',
    43: 'Dense fog',
    44: 'Stable fog',
    45: 'Dense fog',
    46: 'Thick fog',
    47: 'Dense fog',
    48: 'Rime fog',
    49: 'Rime dense fog',
    50: 'Intermittent drizzle',
    51: 'Continuous drizzle',
    52: 'Moderate drizzle',
    53: 'Continuous drizzle',
    54: 'Heavy drizzle',
    55: 'Heavy continuous drizzle',
    56: 'Light freezing drizzle',
    57: 'Heavy freezing drizzle',
    58: 'Light rain',
    59: 'Heavy rain',
    60: 'Light rain',
    61: 'Continuous light rain',
    62: 'Moderate rain',
    63: 'Continuous rain',
    64: 'Heavy rain',
    65: 'Continuous heavy rain',
    66: 'Light freezing rain',
    67: 'Heavy freezing rain',
    68: 'Light mixed',
    69: 'Heavy mixed',
    70: 'Light snow',
    71: 'Continuous snow',
    72: 'Moderate snow',
    73: 'Continuous snow',
    74: 'Heavy snow',
    75: 'Continuous heavy snow',
    76: 'Diamond dust',
    77: 'Snow grains',
    78: 'Snow crystals',
    79: 'Ice pellets',
    80: 'Light showers',
    81: 'Heavy showers',
    82: 'Violent showers',
    83: 'Light mixed showers',
    84: 'Heavy mixed showers',
    85: 'Light snow showers',
    86: 'Heavy snow showers',
    87: 'Light hail',
    88: 'Heavy hail',
    89: 'Light hail showers',
    90: 'Heavy hail showers',
    91: 'Post-thunderstorm rain',
    92: 'Heavy rain',
    93: 'Light mixed',
    94: 'Heavy mixed',
    95: 'Mild thunderstorm',
    96: 'Mild hailstorm',
    97: 'Heavy thunderstorm',
    98: 'Storm with dust',
    99: 'Severe hailstorm'
};
export default weatherCodeDescription;