const weatherCodeDescription = {
    0: 'Clear sky',
    1: 'Mainly clear, some clouds',
    2: 'Partly cloudy',
    3: 'Overcast',
    4: 'Visibility reduced by smoke',
    5: 'Haze',
    6: 'Widespread dust in air',
    7: 'Dust or sand raised by wind',
    8: 'Well-developed dust/sand whirls',
    9: 'Duststorm or sandstorm',
    10: 'Mist',
    11: 'Patches of shallow fog',
    12: 'More or less continuous shallow fog',
    13: 'Lightning visible, no thunder heard',
    14: 'Precipitation within sight, not reaching the ground or surface',
    15: 'Precipitation within sight, reaching the ground but distant (more than 5km away)',
    16: 'Precipitation within sight, reaching the ground nearby (less than 5km)',
    17: 'Thunderstorm, but no precipitation at the station',
    18: 'Squalls within sight, but no precipitation at the station',
    19: 'Funnel clouds within sight',
    20: "Drizzle or snow grains, not in showers",
    21: "Rain, not freezing",
    22: "Snowfall",
    23: "Rain and snow or ice pellets observed",
    24: "Freezing drizzle or freezing rain",
    25: "Rain showers observed",
    26: "Snow showers or rain and snow showers observed",
    27: "Hail showers or rain and hail showers observed",
    28: "Fog present",
    29: "Thunderstorm observed (with or without precipitation)",
    30: "Slight or moderate duststorm or sandstorm, decreasing over the preceding hour",
    31: "No significant change in weather",
    32: "Weather change started or intensified",
    33: "Severe duststorm or sandstorm, decreasing",
    34: "No significant change in weather",
    35: "Weather change started or intensified",
    36: "Light or moderate blowing snow (low)",
    37: "Heavy drifting snow",
    38: "Light or moderate blowing snow (high)",
    39: "Heavy drifting snow",
    40: "Fog observed at a distance",
    41: "Patches of Fog observed",
    42: "Fog observed, thinner",
    43: "Fog observed, invisible sky",
    44: "Fog observed, no significant change",
    45: "Fog observed, invisible sky",
    46: "Fog observed, thicker",
    47: "Fog observed, invisible sky",
    48: "Fog observed, depositing rime",
    49: "Fog observed, depositing rime, invisible sky",
    50: "Intermittent slight drizzle (non-freezing)",
    51: "Continuous slight drizzle (non-freezing)",
    52: "Intermittent moderate drizzle (non-freezing)",
    53: "Continuous drizzle (non-freezing)",
    54: "Intermittent heavy drizzle (non-freezing)",
    55: "Continuous heavy drizzle (non-freezing)",
    56: "Slight freezing drizzle",
    57: "Moderate to heavy freezing drizzle",
    58: "Slight drizzle and rain",
    59: "Moderate to heavy drizzle and rain",
    60: "Intermittent slight rain",
    61: "Continuous slight rain",
    62: "Intermittent moderate rain",
    63: "Continuous moderate rain",
    64: "Intermittent heavy rain",
    65: "Continuous heavy rain",
    66: "Slight freezing rain",
    67: "Moderate to heavy freezing rain",
    68: "Slight rain or drizzle and snow",
    69: "Moderate to heavy rain or drizzle and snow",
    70: "Intermittent slight snowfall",
    71: "Continuous snowfall",
    72: "Intermittent moderate snowfall",
    73: "Continuous snowfall",
    74: "Intermittent heavy snowfall",
    75: "Continuous snowfall",
    76: "Diamond dust (with or without fog)",
    77: "Snow grains (with or without fog)",
    78: "Isolated star-like snow crystals (with or without fog)",
    79: "Ice pellets",
    80: "Slight rain showers",
    81: "Moderate to heavy rain showers",
    82: "Violent rain showers",
    83: "Slight rain and snow showers",
    84: "Moderate to heavy rain and snow showers",
    85: "Slight snow showers",
    86: "Moderate to heavy snow showers",
    87: "Slight snow pellets or small hail showers",
    88: "Moderate to heavy snow pellets or small hail showers",
    89: "Slight hail showers (without thunder)",
    90: "Moderate to heavy hail showers (without thunder)",
    91: "Slight rain observed, previous thunderstorm",
    92: "Moderate to heavy rain observed",
    93: "Slight snow or rain and snow or hail observed",
    94: "Moderate to heavy snow or rain and snow or hail observed",
    95: "Slight to moderate thunderstorm, no hail, with rain",
    96: "Slight to moderate thunderstorm with hail",
    97: "Heavy thunderstorm, no hail, with rain",
    98: "Thunderstorm combined with duststorm or sandstorm",
    99: "Heavy thunderstorm with hail"
};

export default weatherCodeDescription;