const weatherCodeDescription = {
    0: "No cloud development observed",
    1: "Clouds dissipating or less developed",
    2: "Sky condition unchanged",
    3: "Clouds forming or developing",
    4: "Reduced visibility due to smoke (e.g., wildfires, industrial, volcanic)",
    5: "Haze present",
    6: "Dust suspended in air, not wind-raised at observation",
    7: "Dust or sand raised by wind, no significant dust/sand whirls or storms",
    8: "Dust or sand whirls observed, no significant storms",
    9: "Duststorm or sandstorm observed",
    10: "Mist present",
    11: "Shallow fog or ice fog",
    12: "Continuous fog or ice fog",
    13: "Visible lightning, no audible thunder",
    14: "Visible precipitation, not reaching the ground or sea surface",
    15: "Visible precipitation, reaching ground or sea surface, distant (over 5 km)",
    16: "Visible precipitation, reaching ground or sea surface, nearby but not at station",
    17: "Thunderstorm observed, no precipitation at observation time",
    18: "Squalls observed at or near the station",
    19: "Funnel cloud(s) observed",
    20: "Drizzle or snow grains, not in showers",
    21: "Rain, not freezing",
    22: "Snowfall",
    23: "Rain and snow or ice pellets observed",
    24: "Freezing drizzle or freezing rain",
    25: "Rain showers observed",
    26: "Snow showers or rain and snow showers observed",
    27: "Hail showers or rain and hail showers observed",
    28: "Fog or ice fog present",
    29: "Thunderstorm observed (with or without precipitation)",
    30: "Slight or moderate duststorm or sandstorm, decreasing over the preceding hour",
    31: "No significant change in weather",
    32: "Weather change started or intensified",
    33: "Severe duststorm or sandstorm, decreasing",
    34: "No significant change in weather",
    35: "Weather change started or intensified",
    36: "Light or moderate blowing snow (low)",
    37: "Heavy drifting snow",
    38: "Light or moderate blowing snow (high)",
    39: "Heavy drifting snow",
    40: "Fog or ice fog observed at a distance",
    41: "Patches of fog or ice fog observed",
    42: "Fog or ice fog observed, thinner",
    43: "Fog or ice fog observed, invisible sky",
    44: "Fog or ice fog observed, no significant change",
    45: "Fog or ice fog observed, invisible sky",
    46: "Fog or ice fog observed, thicker",
    47: "Fog or ice fog observed, invisible sky",
    48: "Fog observed, depositing rime",
    49: "Fog observed, depositing rime, invisible sky",
    50: "Intermittent slight drizzle (non-freezing)",
    51: "Continuous slight drizzle (non-freezing)",
    52: "Intermittent moderate drizzle (non-freezing)",
    53: "Continuous drizzle (non-freezing)",
    54: "Intermittent heavy drizzle (non-freezing)",
    55: "Continuous heavy drizzle (non-freezing)",
    56: "Slight freezing drizzle",
    57: "Moderate to heavy freezing drizzle",
    58: "Slight drizzle and rain",
    59: "Moderate to heavy drizzle and rain",
    60: "Intermittent slight rain",
    61: "Continuous slight rain",
    62: "Intermittent moderate rain",
    63: "Continuous moderate rain",
    64: "Intermittent heavy rain",
    65: "Continuous heavy rain",
    66: "Slight freezing rain",
    67: "Moderate to heavy freezing rain",
    68: "Slight rain or drizzle and snow",
    69: "Moderate to heavy rain or drizzle and snow",
    70: "Intermittent slight snowfall",
    71: "Continuous snowfall",
    72: "Intermittent moderate snowfall",
    73: "Continuous snowfall",
    74: "Intermittent heavy snowfall",
    75: "Continuous snowfall",
    76: "Diamond dust (with or without fog)",
    77: "Snow grains (with or without fog)",
    78: "Isolated star-like snow crystals (with or without fog)",
    79: "Ice pellets",
    80: "Slight rain showers",
    81: "Moderate to heavy rain showers",
    82: "Violent rain showers",
    83: "Slight rain and snow showers",
    84: "Moderate to heavy rain and snow showers",
    85: "Slight snow showers",
    86: "Moderate to heavy snow showers",
    87: "Slight snow pellets or small hail showers",
    88: "Moderate to heavy snow pellets or small hail showers",
    89: "Slight hail showers (without thunder)",
    90: "Moderate to heavy hail showers (without thunder)",
    91: "Slight rain observed, previous thunderstorm",
    92: "Moderate to heavy rain observed",
    93: "Slight snow or rain and snow or hail observed",
    94: "Moderate to heavy snow or rain and snow or hail observed",
    95: "Slight to moderate thunderstorm, no hail, with rain and/or snow",
    96: "Slight to moderate thunderstorm with hail",
    97: "Heavy thunderstorm, no hail, with rain and/or snow",
    98: "Thunderstorm combined with duststorm or sandstorm",
    99: "Heavy thunderstorm with hail"
};

export default weatherCodeDescription;